### ISSUE TITLE
WEMOS XI Pico

### ISSUE THREAD

**Issue by vuhazu** [kenneth558/plant_resistance_primary_perception#4]
do you know it? i can't use pico with LGT328D SSOP20
Please tell me if you know
thanks

**Comment by kenneth558** [comment]
I had never heard of the Pico, so I read a little about it.  I've never touched one, but I know that not all Arduino-type microcontrollers come with built-in bootloader code, so many require very unique means of loading a sketch into them.  I'll be of no use to you whatsoever beyond that, nor can anyone else if you don't specifically say what you are observing that leads you to say "can't use".  Don't bother telling me - I wouldn't know squat about it.  Just be aware that if you do find someone knowledgeable, they will need to know EXACTLY what you see, taste, smell, etc. and which operating system you're using and which type of cable your computer is connected to the device with including power supply voltage.  Beyond that, I am concluding from all my Arduino experience that you'll be more likely to have success if you're using Windows instead of Linux or Mac.

**Comment by vuhazu** [comment]
Hi. Thanks for reply
I use Window but it ok for LGT328 QFP32 or ALPHA ARDUINO by on taobao.com
i use bootloader on https://github.com/LGTMCU/Larduino_HSP . it can burn bootloader but can't build sketch for LGT328D SSOP20 ( have any error)
if i use LGT8FX8D/P系列Arduino硬件支持包(v3.6c) on http://www.lgtic.com/downloads/. it can burn bootloader with some warning and error when i upload sketch.
i think it have some problem from LGT machine  :) and hope on future 
:D
